### ISSUE TITLE
Error when dictionary contains empty element

### ISSUE THREAD

**Issue by MichalOvadek** [koheiw/quanteda.seededlda#1]
Nice and straightforward implementation of a semi-supervised topic model. I accidentally discovered that if your dictionary contains an empty element (""), the function gives an error. Would be useful to have an appropriate error message signalling this; the function would first check the dictionary and give an error if there is something improper.

**Comment by koheiw** [comment]
It should be working now. Please try.

**Comment by MichalOvadek** [comment]
Works now. Thanks.
